export enum tagTypes {
  user = "user",
  party = "party",
  brand = "brand",
  product = "product",
  productCategory = "product-category",
  productSubCategory = "product-sub-category",
  status = "status",
  unitType = "unitType",
  units = "units",
  varients = "varients",
  purchase = "purchase",
  sales = "sales",
  return = "return",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.party,
  tagTypes.brand,
  tagTypes.product,
  tagTypes.productCategory,
  tagTypes.productSubCategory,
  tagTypes.status,
  tagTypes.unitType,
  tagTypes.units,
  tagTypes.varients,
  tagTypes.purchase,
  tagTypes.sales,
  tagTypes.return,
];
